### PR TITLE
Fixup packet SaltCrypt

### PR DESCRIPTION
**Pull request by pallas**
Several bugs, two specific to python3 and one in general.  Pre-this, hostapd can't decode Tunnel-Password. Post-this, it can. The secrets change is unnecessary, but seemed like the Right Thing to Do.

### CODE REVIEW

**Comment by Istvan91** [comment]
Hi, can you please check if it salt encryption works in commit bd795dac5898e71b52922ffb7714093c11810b7c?

I suspect this bug comes from the change after the commit, so instead of merging this i would rather revert the commit introducing the bug.

**Comment by pallas** [comment]
Yeah, happy to try it.

**Comment by pallas** [comment]
`SaltCrypt` does not work at `bd795da` either, however it looks like reverting `54d9d2d` might make `97cad26` unnecessary. I'm going to try with a slightly different stack and will update the PR if that's the case.

**Comment by pallas** [comment]
Even if I revert `54d9d2d`, the above stack is still needed to get hostapd to decode a `Tunnel-Password`.

**Comment by pallas** [comment]
@Istvan91 is there anything you'd like me to change about the PR? As a future improvement, I was thinking that allowing `reply["foo"] = [ (tag0, value0), (tag1, value1), value2 ]` &c. could be interesting.

**Comment by Istvan91** [comment]
@pallas is there any problem with doing `radius_message['Tunnel-Password:1'] = my_password`? That should set the tag to 1.

I've thought about your PR, and I'm very reluctant to use the zero tag - as the standard says it shouldn't be used at all.

I hope we can find a better solution

**Comment by pallas** [comment]
No, I think the interface you suggest would be fine. There are other Tunnel-* attributes that have tags as well.. how do those get formed? My read of the standard is that any out of range tag should be ignored, but not sure.. IIRC hostapd doesn't use the tag for anything.

Would it be better to explicitly tag, e.g.
```
radius_message['Tunnel-Password'] = Tag(1, my_password)
```

**Comment by pallas** [comment]
So Tunnel-Password says
```
   Tag
      The Tag field is one octet in length and is intended to provide a
      means of grouping attributes in the same packet which refer to the
      same tunnel.  Valid values for this field are 0x01 through 0x1F,
      inclusive.  If the value of the Tag field is greater than 0x00 and
      less than or equal to 0x1F, it SHOULD be interpreted as indicating
      which tunnel (of several alternatives) this attribute pertains;
      otherwise, the Tag field SHOULD be ignored.
```

But the other attributes say
```
   Tag
      The Tag field is one octet in length and is intended to provide a
      means of grouping attributes in the same packet which refer to the
      same tunnel.  Valid values for this field are 0x01 through 0x1F,
      inclusive.  If the Tag field is unused, it MUST be zero (0x00).
```

This leads me to believe that zero is OK as a default.

**Comment by pallas** [comment]
Oh, I see, this is existing syntax. The problem is that if the tag is missing, it isn't implicitly added. I'm working on a new version of this fix, since SaltCrypt does need the tag to be separated from the data.

**Comment by pallas** [comment]
Ok, I removed the implicit tag from the pull request. Explicit tags work, but it means that `result["Tunnel-Password"] = value` will never work correctly with `hostapd`, only `result["Tunnel-Password:0"] = value`.

The remaining patches fix salt generation and python3 compatibility issues, plus swaps random.SystemRandom for secrets.SystemRandom if available.

**Comment by Istvan91** [comment]
I guess it should be possible to check if there is a tag already or not and add it if necessary. I'll take a look what how the other Tunnel-Attributes behave without a tag.
(Also I'll check how freeradius is handling this)

**Pull request merged**
